CREATE TABLE BOOK (ID INT AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(45), AUTHOR varchar(45));
INSERT INTO BOOK (ID, TITLE, AUTHOR) VALUES (1, 'lala', 'blabla');
INSERT INTO BOOK (ID, TITLE, AUTHOR) VALUES (2, 'adam', 'adam');
INSERT INTO BOOK (ID, TITLE, AUTHOR) VALUES (3, 'vasya', 'q1w2e3r4');